CREATE TABLE cash_card
(
    ID     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    AMOUNT NUMBER NOT NULL DEFAULT 0
);

insert into cash_card(id,amount)
values(1, 456.45);

insert into cash_card(id,amount)
values(2, 232.32);

insert into cash_card(id,amount)
values(3, 1256.89);